apiVersion: batch.tutorial.jcsr.dev/v1
kind: CronJob
metadata:
  name: cronjob-sample1
spec:
  # Add fields here
  schedule: "*/1 * * * *"
  startingDeadlineSeconds: 60
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
